/*
-- Query: SELECT * FROM hotel.camera
LIMIT 0, 1000

-- Date: 2023-10-05 16:49
*/
INSERT INTO `` (`NUMERO`,`TIPO`,`NLETTI`,`PIANO`,`PREZZO`) VALUES (1,'singola',1,1,60);
INSERT INTO `` (`NUMERO`,`TIPO`,`NLETTI`,`PIANO`,`PREZZO`) VALUES (2,'doppia',2,2,80);
INSERT INTO `` (`NUMERO`,`TIPO`,`NLETTI`,`PIANO`,`PREZZO`) VALUES (3,'tripla',3,3,120);
INSERT INTO `` (`NUMERO`,`TIPO`,`NLETTI`,`PIANO`,`PREZZO`) VALUES (4,'doppia',2,1,80);
INSERT INTO `` (`NUMERO`,`TIPO`,`NLETTI`,`PIANO`,`PREZZO`) VALUES (5,'singola',1,2,55);
INSERT INTO `` (`NUMERO`,`TIPO`,`NLETTI`,`PIANO`,`PREZZO`) VALUES (6,'tripla',3,3,130);
INSERT INTO `` (`NUMERO`,`TIPO`,`NLETTI`,`PIANO`,`PREZZO`) VALUES (7,'singola',1,1,65);
INSERT INTO `` (`NUMERO`,`TIPO`,`NLETTI`,`PIANO`,`PREZZO`) VALUES (8,'doppia',2,2,75);
