INSERT INTO hotel.comfort VALUES
(1, 'televisione', 10.99);

INSERT INTO hotel.contratti VALUES
(1,'indeterminato'),
(2,'determinato'),
(3,'chiamata');

INSERT INTO hotel.mansione VALUES
(1,'Direttore'),
(2,'Receptionist'),
(3,'Cameriere'),
(4,'Cuoco'),
(5,'Magazziniere');

INSERT INTO hotel.nazione VALUES
 (1, 'Russia'),
    (2, 'Germania'),
    (3, 'Regno Unito'),
    (4, 'Francia'),
    (5, 'Italia'),
    (6, 'Spagna'),
    (7, 'Ucraina'),
    (8, 'Polonia'),
    (9, 'Romania'),
    (10, 'Olanda'),
    (11, 'Belgio'),
    (12, 'Grecia'),
    (13, 'Portogallo'),
    (14, 'Repubblica Ceca'),
    (15, 'Ungheria'),
    (16, 'Svezia'),
    (17, 'Austria'),
    (18, 'Bulgaria'),
    (19, 'Danimarca'),
    (20, 'Finlandia'),
    (21, 'Stati Uniti d\'America'),
    (22, 'Cina'),
    (23, 'India'),
    (24, 'Giappone'),
    (25, 'Brasile'),
    (26, 'Messico'),
    (27, 'Indonesia'),
    (28, 'Nigeria'),
    (29, 'Bangladesh'),
    (30, 'Filippine'),
    (31, 'Egitto'),
    (32, 'Vietnam'),
    (33, 'Congo-Kinshasa'),
    (34, 'Iran'),
    (35, 'Turchia'),
    (36, 'Canada'),
    (37, 'Myanmar'),
    (38, 'Sud Africa'),
    (39, 'Corea del Sud'),
    (40, 'Tanzania'),
    (41, 'Colombia'),
    (42, 'Kenya'),
    (43, 'Messico'),
    (44, 'Argentina'),
    (45, 'Uganda'),
    (46, 'Algeria'),
    (47, 'Uzbekistan'),
    (48, 'Iraq'),
    (49, 'Arabia Saudita'),
    (50, 'Australia'),
    (51, 'Altro');
    
INSERT INTO hotel.provincia VALUES
(1, 'Agrigento'),
    (2, 'Alessandria'),
    (3, 'Ancona'),
    (4, 'Aosta'),
    (5, 'Arezzo'),
    (6, 'Ascoli Piceno'),
    (7, 'Asti'),
    (8, 'Avellino'),
    (9, 'Bari'),
    (10, 'Barletta-Andria-Trani'),
    (11, 'Belluno'),
    (12, 'Benevento'),
    (13, 'Bergamo'),
    (14, 'Biella'),
    (15, 'Bologna'),
    (16, 'Bolzano'),
    (17, 'Brescia'),
    (18, 'Brindisi'),
    (19, 'Cagliari'),
    (20, 'Caltanissetta'),
    (21, 'Campobasso'),
    (22, 'Carbonia-Iglesias'),
    (23, 'Caserta'),
    (24, 'Catania'),
    (25, 'Catanzaro'),
    (26, 'Chieti'),
    (27, 'Como'),
    (28, 'Cosenza'),
    (29, 'Cremona'),
    (30, 'Crotone'),
    (31, 'Cuneo'),
    (32, 'Enna'),
    (33, 'Fermo'),
    (34, 'Ferrara'),
    (35, 'Firenze'),
    (36, 'Foggia'),
    (37, 'Forlì-Cesena'),
    (38, 'Frosinone'),
    (39, 'Genova'),
    (40, 'Gorizia'),
    (41, 'Grosseto'),
    (42, 'Imperia'),
    (43, 'Isernia'),
    (44, 'La Spezia'),
    (45, 'Aquila'),
    (46, 'Latina'),
    (47, 'Lecce'),
    (48, 'Lecco'),
    (49, 'Livorno'),
    (50, 'Lodi'),
    (51, 'Lucca'),
    (52, 'Macerata'),
    (53, 'Mantova'),
    (54, 'Massa-Carrara'),
    (55, 'Matera'),
    (56, 'Messina'),
    (57, 'Milano'),
    (58, 'Modena'),
    (59, 'Monza e della Brianza'),
    (60, 'Napoli'),
    (61, 'Novara'),
    (62, 'Nuoro'),
    (63, 'Oristano'),
    (64, 'Padova'),
    (65, 'Palermo'),
    (66, 'Parma'),
    (67, 'Pavia'),
    (68, 'Perugia'),
    (69, 'Pesaro e Urbino'),
    (70, 'Pescara'),
    (71, 'Piacenza'),
    (72, 'Pisa'),
    (73, 'Pistoia'),
    (74, 'Pordenone'),
    (75, 'Potenza'),
    (76, 'Prato'),
    (77, 'Ragusa'),
    (78, 'Ravenna'),
    (79, 'Reggio Calabria'),
    (80, 'Reggio Emilia'),
    (81, 'Rieti'),
    (82, 'Rimini'),
    (83, 'Roma'),
    (84, 'Rovigo'),
    (85, 'Salerno'),
    (86, 'Medio Campidano'),
    (87, 'Siena'),
    (88, 'Siracusa'),
    (89, 'Sondrio'),
    (90, 'Taranto'),
    (91, 'Teramo'),
    (92, 'Terni'),
    (93, 'Torino'),
    (94, 'Ogliastra'),
    (95, 'Trapani'),
    (96, 'Trento'),
    (97, 'Treviso'),
    (98, 'Trieste'),
    (99, 'Udine'),
    (100, 'Varese'),
    (101, 'Venezia'),
    (102, 'Verbano-Cusio-Ossola'),
    (103, 'Vercelli'),
    (104, 'Verona'),
    (105, 'Vibo Valentia'),
    (106, 'Vicenza'),
    (107, 'Viterbo'),
    (108, 'Altro');
    
INSERT INTO hotel.tipologia_utente VALUES 
(1, 'Utente'),
(2, 'Dipendente');
