CREATE TABLE `CITTA` (
  `ID_CITTA` int(4) NOT NULL,
  `NOME_C` varchar(45) NOT NULL,
  `ID_NAZ` int(4) NOT NULL,
  `ID_PROV` int(4) NOT NULL,
  PRIMARY KEY (`ID_CITTA`),
  UNIQUE KEY `ID_CITTA_UNIQUE` (`ID_CITTA`),
  KEY `ID_N_idx` (`ID_NAZ`),
  KEY `PROV_idx` (`ID_PROV`),
  CONSTRAINT `NAZ` FOREIGN KEY (`ID_NAZ`) REFERENCES `NAZIONE` (`ID_NAZ`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `PROV` FOREIGN KEY (`ID_PROV`) REFERENCES `PROVINCIA` (`ID_PROV`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1